x-ctp-env: &ctp-env
  CTP_PROJECT_KEY: ${PROJECT_KEY}
  CTP_CLIENT_ID: ${CLIENT_ID}
  CTP_CLIENT_SECRET: ${CLIENT_SECRET}
  CTP_AUTH_URL: ${AUTH_URL}
  CTP_API_URL: ${API_URL}
  CTP_SCOPES: "manage_project:${PROJECT_KEY}"

services:
  product-service:
    build: product-service
    ports:
      - "8081:8081"
    networks:
      - commercetools-net
    environment:
      <<: *ctp-env
      JAVA_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 600M

  cart-service:
    build: cart-service
    ports:
      - "8082:8082"
    networks:
      - commercetools-net
    environment:
      <<: *ctp-env
      JAVA_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 600M

  customer-service:
    build: customer-service
    ports:
      - "8083:8083"
    networks:
      - commercetools-net
    environment:
      <<: *ctp-env
      JAVA_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 600M

  payment-service:
    build: payment-service
    ports:
      - "8084:8084"
    networks:
      - commercetools-net
    environment:
      <<: *ctp-env
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      JAVA_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 600M

  order-service:
    build: order-service
    ports:
      - "8086:8086"
    networks:
      - commercetools-net
    environment:
      <<: *ctp-env
      JAVA_OPTS: "-Xms256m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 600M

  api-gateway:
    build: api-gateway
    ports:
      - "8085:8080"
    networks:
      - commercetools-net
    environment:
      JAVA_OPTS: "-Xms256m -Xmx512m"
    depends_on:
      - product-service
      - cart-service
      - customer-service
      - payment-service
      - order-service
    deploy:
      resources:
        limits:
          memory: 600M

  frontend:
    build: ../frontend
    ports:
      - "3001:80"
    networks:
      - commercetools-net
    depends_on:
      - api-gateway
    deploy:
      resources:
        limits:
          memory: 600M

  foundational-mcp-server:
    build: ../foundational-mcp-server
    container_name: foundational-mcp-server
    ports:
      - "8087:8000"
    networks:
      - commercetools-net
    environment:
      - API_BASE_URL=http://api-gateway:8080/api
    depends_on:
      - api-gateway
    deploy:
      resources:
        limits:
          memory: 600M


networks:
  commercetools-net:
    driver: bridge
