server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**
        - id: cart-service
          uri: http://cart-service:8082
          predicates:
            - Path=/api/carts/**
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/api/payments/**
        - id: order-service
          uri: http://order-service:8086
          predicates:
            - Path=/api/orders/**
        - id: customer-service
          uri: http://customer-service:8083
          predicates:
            - Path=/api/customers/**
        - id: product-service-docs
          uri: http://product-service:8081
          predicates:
            - Path=/v3/api-docs/product-service
          filters:
            - RewritePath=/v3/api-docs/product-service, /v3/api-docs
        - id: cart-service-docs
          uri: http://cart-service:8082
          predicates:
            - Path=/v3/api-docs/cart-service
          filters:
            - RewritePath=/v3/api-docs/cart-service, /v3/api-docs
        - id: payment-service-docs
          uri: http://payment-service:8084
          predicates:
            - Path=/v3/api-docs/payment-service
          filters:
            - RewritePath=/v3/api-docs/payment-service, /v3/api-docs
        - id: order-service-docs
          uri: http://order-service:8086
          predicates:
            - Path=/v3/api-docs/order-service
          filters:
            - RewritePath=/v3/api-docs/order-service, /v3/api-docs
        - id: customer-service-docs
          uri: http://customer-service:8083
          predicates:
            - Path=/v3/api-docs/customer-service
          filters:
            - RewritePath=/v3/api-docs/customer-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Product Service
        url: /v3/api-docs/product-service
      - name: Cart Service
        url: /v3/api-docs/cart-service
      - name: Customer Service
        url: /v3/api-docs/customer-service
      - name: Order Service
        url: /v3/api-docs/order-service
      - name: Payment Service
        url: /v3/api-docs/payment-service
